# Generated by Django 3.0.6 on 2020-06-06 12:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.TimeField(verbose_name=django.utils.timezone.now),
        ),
    ]
