# Generated by Django 3.0.6 on 2020-06-06 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200606_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
