# Generated by Django 3.0.6 on 2020-06-09 07:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200606_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.TimeField(verbose_name=django.utils.timezone.now),
        ),
    ]
