# Generated by Django 3.0.6 on 2020-06-09 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200609_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
