# Generated by Django 3.0.6 on 2020-06-08 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200608_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='default_profile.jpg', upload_to=''),
        ),
    ]
